<?php

namespace AppBundle\Repository;

/**
 * BaronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaronRepository extends \Doctrine\ORM\EntityRepository
{
}
